---
#=============================  INSTALA SSMTP  ==========================#


 - name: "Instala ssmtp"
   yum:
    name: ssmtp
    state: latest


#=============================  CONFIGURA SSMTP ===============================#

 - name: "Configurando SSMTP para envio do relatório"
   blockinfile:
    path: /etc/ssmtp/revaliases
    block: |
        root:desafiolinx@gmail.com:smtp.gmail.com:587


 - name: 'Copia arquivo ssmtp.conf'
   copy:
    src: "./files/ssmtp.conf"
    dest: "/etc/ssmtp/ssmtp.conf"


