---
#==================  COPIANDO SCRIPTS CARGA.SH E PARSERLOG PARA SERVIDOR REMOTO  =====================#

 - file:
     path: '/opt/scripts'
     state: directory
     mode: 0755

 - copy:
     src: files/{{ item }}
     dest: /opt/scripts
   with_items:
     - parserlog.sh
     - carga.sh

 - file:
     path: /opt/scripts/{{ item }}
     mode: 0655
   with_items:
     - parserlog.sh
     - carga.sh

#==================  CRIANDO CRON PARA EXECUTAR GERAR RELATORIO DE REQUISICOES E ENVIAR E-MAIL  =====================#

 - cron:
     name: "Executa parser_log.sh"
     minute: "0"
     hour: "2"
     job: "/bin/bash /opt/scripts/parserlog.sh > /dev/null"
